FROM registry.redhat.io/rhel9/rhel-bootc:9.6

RUN dnf -y install dnf-plugins-core && \
  dnf -y copr enable @redhat-et/flightctl rhel-9-x86_64  && \
  dnf -y install flightctl-agent flightctl-selinux && \
  dnf -y clean all && \
  systemctl enable flightctl-agent.service && \
  systemctl mask bootc-fetch-apply-updates.timer

# Enable fips=1 kernel argument: https://bootc-dev.github.io/bootc/building/kernel-arguments.html
COPY 01-fips.toml /usr/lib/bootc/kargs.d/
# Install and enable the FIPS crypto policy
RUN dnf install -y crypto-policies-scripts && update-crypto-policies --no-reload --set FIPS
# Optional: To enable podman-compose application support, uncomment below
RUN dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm && \
  dnf -y install podman-compose && \
  dnf -y clean all && \
  rm -rf /var/{cache,log} /var/lib/{dnf,rhsm} && \
  systemctl enable podman.service

ADD config.yaml /etc/flightctl/
